version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["pipenv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile # or Dockerfile_UI
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app                   # Mount all your code (for hot reload)
      - ui_node_modules:/app/node_modules # But overlay node_modules ONLY as a Docker volume
    environment:
      - NODE_ENV=development
    command: ["bun", "run", "dev", "--host", "0.0.0.0", "--port=3000"]

volumes:
  ui_node_modules:
